name: Tests CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn test

      - name: Tests ✅
        if: ${{ success() }}
        run: echo "Tests passed. Deploying - "

      - name: Tests 🚨
        if: ${{ failure() }}
        run: echo "Tests failed, aborting deploy."